#!/usr/bin/env bash
# Auto-generated by stage1_generate_cmds.py - SFC-DP ablation grid
# Stage 1 SFC-DP ablation grid

set -euo pipefail

ZARR_PATH="/home/Travor/workspaces/diffusion_policy/data/pusht/pusht_cchi_v7_replay.zarr"
DP_REPO="/home/Travor/workspaces/diffusion_policy"
RUNS_DIR="/mnt/d/Code/Learning/EI/EI-learning-notes/Diffusion_Policy/artifacts/sfc_runs"

mkdir -p "$RUNS_DIR"

# ── Group A: baseline: standard DP, no L_freq
echo '>>> group=A seed=42'
python /mnt/d/Code/Learning/EI/EI-learning-notes/Diffusion_Policy/sfc_dp/train_sfc.py --group A --seed 42 --epochs 100 --batch-size 16 --lr 0.0001 --lambda-freq 0.001 --lambda-warmup-epochs 20 --zarr-path "$ZARR_PATH" --dp-repo "$DP_REPO" --outdir "$RUNS_DIR"/A_seed42

# ── Group B: full-band mask (no SNR alignment), ablates SNR masking
echo '>>> group=B seed=42'
python /mnt/d/Code/Learning/EI/EI-learning-notes/Diffusion_Policy/sfc_dp/train_sfc.py --group B --seed 42 --epochs 100 --batch-size 16 --lr 0.0001 --lambda-freq 0.001 --lambda-warmup-epochs 20 --zarr-path "$ZARR_PATH" --dp-repo "$DP_REPO" --outdir "$RUNS_DIR"/B_seed42

# ── Group C: SNR mask in epsilon-space, ablates x0 prediction space
echo '>>> group=C seed=42'
python /mnt/d/Code/Learning/EI/EI-learning-notes/Diffusion_Policy/sfc_dp/train_sfc.py --group C --seed 42 --epochs 100 --batch-size 16 --lr 0.0001 --lambda-freq 0.001 --lambda-warmup-epochs 20 --zarr-path "$ZARR_PATH" --dp-repo "$DP_REPO" --outdir "$RUNS_DIR"/C_seed42

# ── Group D: SFC-DP full: L_freq + SNR mask + x0_hat_k, main method
echo '>>> group=D seed=42'
python /mnt/d/Code/Learning/EI/EI-learning-notes/Diffusion_Policy/sfc_dp/train_sfc.py --group D --seed 42 --epochs 100 --batch-size 16 --lr 0.0001 --lambda-freq 0.001 --lambda-warmup-epochs 20 --zarr-path "$ZARR_PATH" --dp-repo "$DP_REPO" --outdir "$RUNS_DIR"/D_seed42

# ── Group E: stop-grad on x0_hat_k, ablates gradient path through epsilon_theta
echo '>>> group=E seed=42'
python /mnt/d/Code/Learning/EI/EI-learning-notes/Diffusion_Policy/sfc_dp/train_sfc.py --group E --seed 42 --epochs 100 --batch-size 16 --lr 0.0001 --lambda-freq 0.001 --lambda-warmup-epochs 20 --zarr-path "$ZARR_PATH" --dp-repo "$DP_REPO" --outdir "$RUNS_DIR"/E_seed42

echo '=== SFC-DP ablation grid complete ==='
