"""
Stage 1 - Generate SFC-DP ablation run commands.

Produces a bash script for Stage 1 ablations.

Default behavior matches the first-pass plan:
    5 groups (A-E) x 1 seed (42) = 5 runs

If you want confirmatory runs as well:
    --seeds 42 43

Use --groups to run a subset (e.g. --groups A D for quick A vs D):
    python stage1_generate_cmds.py --groups A D

Use --lambda-sweep to generate a λ sensitivity grid (group D × seed 42):
    python stage1_generate_cmds.py --lambda-sweep

Use --epochs 200 for extended training:
    python stage1_generate_cmds.py --groups A D --epochs 200

Groups:
    A — baseline: standard DP, no L_freq
    B — L_freq full-band mask (no SNR alignment)
    C — L_freq + SNR mask in ε-space
    D — SFC-DP full: L_freq + SNR mask + x̂₀|k  ← MAIN METHOD
    E — same as D but stop-grad on x̂₀|k

Usage
-----
    python stage1_generate_cmds.py [options]
    bash artifacts/run_sfc_grid.sh
"""
from __future__ import annotations

import argparse
import stat
from pathlib import Path


GROUPS = ["A", "B", "C", "D", "E"]
DEFAULT_SEEDS = [42]
LAMBDA_SWEEP_VALUES = [0.003, 0.01, 0.03]  # 3×, 10×, 30× relative to 0.001 default

GROUP_DESC = {
    "A": "baseline: standard DP, no L_freq",
    "B": "full-band mask (no SNR alignment), ablates SNR masking",
    "C": "SNR mask in epsilon-space, ablates x0 prediction space",
    "D": "SFC-DP full: L_freq + SNR mask + x0_hat_k, main method",
    "E": "stop-grad on x0_hat_k, ablates gradient path through epsilon_theta",
}


def to_wsl_path(path_str: str) -> str:
    path = Path(path_str)
    drive = path.drive.rstrip(":")
    if drive:
        suffix = path.as_posix().split(":", 1)[1]
        return f"/mnt/{drive.lower()}{suffix}"
    return path.as_posix()


def build_cmd(
    group: str,
    seed: int,
    zarr_path: str,
    dp_repo: str,
    runs_outdir: str,
    script_dir: str,
    epochs: int,
    batch_size: int,
    lr: float,
    lambda_freq: float,
    lambda_warmup_epochs: int,
    soft_mask: bool,
    soft_mask_tau: float,
) -> str:
    run_dir = f"{runs_outdir}/{group}_seed{seed}"
    cmd = (
        f"python {script_dir}/train_sfc.py"
        f" --group {group}"
        f" --seed {seed}"
        f" --epochs {epochs}"
        f" --batch-size {batch_size}"
        f" --lr {lr}"
        f" --lambda-freq {lambda_freq}"
        f" --lambda-warmup-epochs {lambda_warmup_epochs}"
        f" --zarr-path {zarr_path}"
        f" --dp-repo {dp_repo}"
        f" --outdir {run_dir}"
    )
    if soft_mask:
        cmd += " --soft-mask"
        cmd += f" --soft-mask-tau {soft_mask_tau}"
    return cmd


def generate_lambda_sweep_script(args: argparse.Namespace) -> str:
    """Generate a λ sensitivity sweep: group D × seed 42 × LAMBDA_SWEEP_VALUES."""
    lines = [
        "#!/usr/bin/env bash",
        "# Auto-generated by stage1_generate_cmds.py - SFC-DP λ sweep",
        "# Purpose: find λ_freq that keeps L_freq active throughout 100 epochs",
        "# Runs: group D × seed 42 × λ ∈ [0.003, 0.01, 0.03]",
        "",
        "set -euo pipefail",
        "",
        f'ZARR_PATH="{args.zarr_path}"',
        f'DP_REPO="{args.dp_repo}"',
        f'RUNS_DIR="{args.outdir}"',
        "",
        'mkdir -p "$RUNS_DIR"',
        "",
    ]
    for lam in LAMBDA_SWEEP_VALUES:
        tag = f"lam{lam}".replace(".", "p")
        run_dir = '"$RUNS_DIR"' + f"/D_seed42_{tag}"
        cmd = (
            f"python {to_wsl_path(str(Path(args.script_dir).resolve()))}/train_sfc.py"
            f" --group D"
            f" --seed 42"
            f" --epochs {args.epochs}"
            f" --batch-size {args.batch_size}"
            f" --lr {args.lr}"
            f" --lambda-freq {lam}"
            f" --lambda-warmup-epochs {args.lambda_warmup_epochs}"
            f" --zarr-path \"$ZARR_PATH\""
            f" --dp-repo \"$DP_REPO\""
            f" --outdir {run_dir}"
        )
        lines.append(f"echo '>>> λ={lam}'")
        lines.append(cmd)
        lines.append("")
    lines.append("echo '=== λ sweep complete ==='")
    return "\n".join(lines) + "\n"


def generate_script(args: argparse.Namespace) -> str:
    groups_to_run = args.groups if args.groups else GROUPS
    lines = [
        "#!/usr/bin/env bash",
        "# Auto-generated by stage1_generate_cmds.py - SFC-DP ablation grid",
        f"# Groups: {groups_to_run}  Seeds: {args.seeds}",
        "",
        "set -euo pipefail",
        "",
        f'ZARR_PATH="{args.zarr_path}"',
        f'DP_REPO="{args.dp_repo}"',
        f'RUNS_DIR="{args.outdir}"',
        "",
        'mkdir -p "$RUNS_DIR"',
        "",
    ]

    for group in groups_to_run:
        lines.append(f"# ── Group {group}: {GROUP_DESC[group]}")
        for seed in args.seeds:
            cmd = build_cmd(
                group=group,
                seed=seed,
                zarr_path='"$ZARR_PATH"',
                dp_repo='"$DP_REPO"',
                runs_outdir='"$RUNS_DIR"',
                script_dir=to_wsl_path(str(Path(args.script_dir).resolve())),
                epochs=args.epochs,
                batch_size=args.batch_size,
                lr=args.lr,
                lambda_freq=args.lambda_freq,
                lambda_warmup_epochs=args.lambda_warmup_epochs,
                soft_mask=args.soft_mask,
                soft_mask_tau=args.soft_mask_tau,
            )
            lines.append(f"echo '>>> group={group} seed={seed}'")
            lines.append(cmd)
            lines.append("")

    lines.append("echo '=== SFC-DP ablation grid complete ==='")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate SFC-DP Stage 1 ablation run commands."
    )
    parser.add_argument(
        "--zarr-path", type=str,
        default="/home/Travor/workspaces/diffusion_policy/data/pusht/pusht_cchi_v7_replay.zarr",
    )
    parser.add_argument(
        "--dp-repo", type=str,
        default="/home/Travor/workspaces/diffusion_policy",
    )
    parser.add_argument(
        "--outdir", type=str,
        default="/mnt/d/Code/Learning/EI/EI-learning-notes/Diffusion_Policy/artifacts/sfc_runs",
        help="Parent directory for run output folders.",
    )
    parser.add_argument(
        "--script-out", type=str,
        default="/mnt/d/Code/Learning/EI/EI-learning-notes/Diffusion_Policy/artifacts/run_sfc_grid.sh",
        help="Output path for the generated bash script.",
    )
    parser.add_argument(
        "--script-dir", type=str,
        default=str(Path(__file__).resolve().parent),
        help="Directory containing train_sfc.py.",
    )
    parser.add_argument("--epochs",      type=int,   default=100,
                        help="Training epochs per run. Use 200 for extended convergence check.")
    parser.add_argument("--batch-size",  type=int,   default=16)
    parser.add_argument("--lr",          type=float, default=1e-4)
    parser.add_argument("--lambda-freq", type=float, default=0.001,
                        help="Weight on L_freq for groups B–E.")
    parser.add_argument("--lambda-warmup-epochs", type=int, default=20)
    parser.add_argument("--soft-mask", action="store_true")
    parser.add_argument("--soft-mask-tau", type=float, default=0.05)
    parser.add_argument("--seeds", type=int, nargs="+", default=DEFAULT_SEEDS)
    parser.add_argument(
        "--groups", type=str, nargs="+", default=None,
        choices=GROUPS,
        help="Subset of groups to include (default: all A-E). E.g. --groups A D",
    )
    parser.add_argument(
        "--lambda-sweep", action="store_true",
        help=(
            "Generate a λ sensitivity sweep instead of the standard grid. "
            f"Runs group D × seed 42 × λ ∈ {LAMBDA_SWEEP_VALUES}. "
            "Ignores --groups and --seeds."
        ),
    )
    args = parser.parse_args()

    if args.lambda_sweep:
        script = generate_lambda_sweep_script(args)
        sweep_out = Path(args.script_out).with_name("run_lambda_sweep.sh")
        sweep_out.parent.mkdir(parents=True, exist_ok=True)
        sweep_out.write_text(script, encoding="utf-8")
        try:
            mode = sweep_out.stat().st_mode
            sweep_out.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        except (AttributeError, NotImplementedError):
            pass
        print(f"Generated λ sweep: {sweep_out}")
        print(f"  λ values: {LAMBDA_SWEEP_VALUES}")
        print(f"\nRun with:\n  bash {sweep_out}")
        return

    script = generate_script(args)

    out = Path(args.script_out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(script, encoding="utf-8")
    try:
        mode = out.stat().st_mode
        out.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    except (AttributeError, NotImplementedError):
        pass

    groups_ran = args.groups if args.groups else GROUPS
    print(f"Generated: {out}")
    print(f"  Groups : {groups_ran}")
    print(f"  Seeds  : {args.seeds}")
    print(f"  Epochs : {args.epochs}")
    print(f"  Total  : {len(groups_ran) * len(args.seeds)} runs")
    print(f"\nRun with:\n  bash {out}")

    print("\n--- script preview (first 20 lines) ---")
    for line in script.split("\n")[:20]:
        print(line.encode("ascii", errors="replace").decode("ascii"))


if __name__ == "__main__":
    main()
