"""
Stage 1 — Generate SFC-DP ablation run commands.

Produces a bash script with all ablation runs:
    5 groups (A–E) × 2 seeds = 10 runs

Groups:
    A — baseline: standard DP, no L_freq
    B — L_freq full-band mask (no SNR alignment)
    C — L_freq + SNR mask in ε-space
    D — SFC-DP full: L_freq + SNR mask + x̂₀|k  ← MAIN METHOD
    E — same as D but stop-grad on x̂₀|k

Usage
-----
    python stage1_generate_cmds.py [options]
    bash artifacts/run_sfc_grid.sh
"""
from __future__ import annotations

import argparse
import stat
from pathlib import Path


GROUPS = ["A", "B", "C", "D", "E"]
SEEDS  = [42, 43]

GROUP_DESC = {
    "A": "baseline: standard DP, no L_freq",
    "B": "full-band mask (no SNR alignment) — ablates SNR masking",
    "C": "SNR mask in ε-space — ablates x₀ prediction space",
    "D": "SFC-DP full: L_freq + SNR mask + x̂₀|k  ← MAIN METHOD",
    "E": "stop-grad on x̂₀|k — ablates gradient path through ε_θ",
}


def build_cmd(
    group: str,
    seed: int,
    zarr_path: str,
    dp_repo: str,
    runs_outdir: str,
    script_dir: str,
    epochs: int,
    batch_size: int,
    lr: float,
    lambda_freq: float,
) -> str:
    run_dir = f"{runs_outdir}/{group}_seed{seed}"
    return (
        f"python {script_dir}/train_sfc.py"
        f" --group {group}"
        f" --seed {seed}"
        f" --epochs {epochs}"
        f" --batch-size {batch_size}"
        f" --lr {lr}"
        f" --lambda-freq {lambda_freq}"
        f" --zarr-path {zarr_path}"
        f" --dp-repo {dp_repo}"
        f" --outdir {run_dir}"
    )


def generate_script(args: argparse.Namespace) -> str:
    lines = [
        "#!/usr/bin/env bash",
        "# Auto-generated by stage1_generate_cmds.py — SFC-DP ablation grid",
        "# 5 groups × 2 seeds = 10 runs",
        "",
        "set -euo pipefail",
        "",
        f'ZARR_PATH="{args.zarr_path}"',
        f'DP_REPO="{args.dp_repo}"',
        f'RUNS_DIR="{args.outdir}"',
        "",
        'mkdir -p "$RUNS_DIR"',
        "",
    ]

    for group in GROUPS:
        lines.append(f"# ── Group {group}: {GROUP_DESC[group]}")
        for seed in SEEDS:
            cmd = build_cmd(
                group=group,
                seed=seed,
                zarr_path='"$ZARR_PATH"',
                dp_repo='"$DP_REPO"',
                runs_outdir='"$RUNS_DIR"',
                script_dir=str(Path(args.script_dir).resolve()),
                epochs=args.epochs,
                batch_size=args.batch_size,
                lr=args.lr,
                lambda_freq=args.lambda_freq,
            )
            lines.append(f"echo '>>> group={group} seed={seed}'")
            lines.append(cmd)
            lines.append("")

    lines.append("echo '=== SFC-DP ablation grid complete ==='")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate SFC-DP Stage 1 ablation run commands."
    )
    parser.add_argument(
        "--zarr-path", type=str,
        default="/home/Travor/workspaces/diffusion_policy/data/pusht/pusht_cchi_v7_replay.zarr",
    )
    parser.add_argument(
        "--dp-repo", type=str,
        default="/home/Travor/workspaces/diffusion_policy",
    )
    parser.add_argument(
        "--outdir", type=str,
        default="/mnt/d/Code/Learning/EI/EI-learning-notes/Diffusion_Policy/artifacts/sfc_runs",
        help="Parent directory for run output folders.",
    )
    parser.add_argument(
        "--script-out", type=str,
        default="/mnt/d/Code/Learning/EI/EI-learning-notes/Diffusion_Policy/artifacts/run_sfc_grid.sh",
        help="Output path for the generated bash script.",
    )
    parser.add_argument(
        "--script-dir", type=str,
        default=str(Path(__file__).resolve().parent),
        help="Directory containing train_sfc.py.",
    )
    parser.add_argument("--epochs",      type=int,   default=3000)
    parser.add_argument("--batch-size",  type=int,   default=64)
    parser.add_argument("--lr",          type=float, default=1e-4)
    parser.add_argument("--lambda-freq", type=float, default=0.1,
                        help="Weight on L_freq for groups B–E.")
    args = parser.parse_args()

    script = generate_script(args)

    out = Path(args.script_out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(script, encoding="utf-8")
    try:
        mode = out.stat().st_mode
        out.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    except (AttributeError, NotImplementedError):
        pass

    print(f"Generated: {out}")
    print(f"  Groups : {GROUPS}")
    print(f"  Seeds  : {SEEDS}")
    print(f"  Total  : {len(GROUPS) * len(SEEDS)} runs")
    print(f"\nRun with:\n  bash {out}")

    print("\n--- script preview (first 40 lines) ---")
    for line in script.split("\n")[:40]:
        print(line)


if __name__ == "__main__":
    main()
