"""生成 PHRew-DP 的整套实验命令。"""
from __future__ import annotations

import argparse
import stat
from pathlib import Path


MODES = ["uniform", "hard", "soft_hard", "easy"]
SEEDS = [42, 43]

MODE_DESC = {
    "uniform":   "standard DP baseline (uniform sampling)",
    "hard":      "hard-chunk focus: weights ∝ hardness^alpha",
    "soft_hard": "PHRew-DP main: weights ∝ softmax(h/T)   ← MAIN METHOD",
    "easy":      "easy-chunk focus: ablation (expected to be worse)",
}


def build_cmd(
    mode: str,
    seed: int,
    chunk_hardness: str,
    zarr_path: str,
    dp_repo: str,
    runs_outdir: str,
    script_dir: str,
    epochs: int,
    batch_size: int,
    lr: float,
    temperature: float,
    alpha: float,
) -> str:
    run_dir = f"{runs_outdir}/{mode}_seed{seed}"
    return (
        f"python {script_dir}/stage3_train_phrew.py"
        f" --mode {mode}"
        f" --seed {seed}"
        f" --epochs {epochs}"
        f" --batch-size {batch_size}"
        f" --lr {lr}"
        f" --temperature {temperature}"
        f" --alpha {alpha}"
        f" --chunk-hardness {chunk_hardness}"
        f" --zarr-path {zarr_path}"
        f" --dp-repo {dp_repo}"
        f" --outdir {run_dir}"
    )


def generate_script(args: argparse.Namespace) -> str:
    lines = [
        "#!/usr/bin/env bash",
        "# Generated by stage4_generate_cmds.py",
        "# 4 modes x 2 seeds = 8 runs",
        "",
        "set -euo pipefail",
        "",
        f'ZARR_PATH="{args.zarr_path}"',
        f'DP_REPO="{args.dp_repo}"',
        f'RUNS_DIR="{args.outdir}"',
        f'CHUNK_H="{args.chunk_hardness}"',
        "",
        'mkdir -p "$RUNS_DIR"',
        "",
        "# 如果 chunk hardness 还没生成，先跑 Stage 2b",
        f'if [ ! -f "$CHUNK_H" ]; then',
        f'  echo ">>> Running Stage 2b: chunk scoring"',
        f'  python {str(Path(args.script_dir).resolve())}/stage2b_score_chunks.py \\',
        f'    --zarr-path "$ZARR_PATH" \\',
        f'    --checkpoint {args.probe_checkpoint} \\',
        f'    --outdir "$(dirname "$CHUNK_H")"',
        'fi',
        "",
    ]

    for mode in MODES:
        lines.append(f"# mode: {mode} — {MODE_DESC[mode]}")
        for seed in SEEDS:
            cmd = build_cmd(
                mode=mode,
                seed=seed,
                chunk_hardness='"$CHUNK_H"',
                zarr_path='"$ZARR_PATH"',
                dp_repo='"$DP_REPO"',
                runs_outdir='"$RUNS_DIR"',
                script_dir=str(Path(args.script_dir).resolve()),
                epochs=args.epochs,
                batch_size=args.batch_size,
                lr=args.lr,
                temperature=args.temperature,
                alpha=args.alpha,
            )
            lines.append(f"echo '>>> mode={mode} seed={seed}'")
            lines.append(cmd)
            lines.append("")

    lines.append("echo '=== PHRew-DP grid complete ==='")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate PHRew-DP Stage 3 comparison run commands."
    )
    parser.add_argument(
        "--zarr-path",
        type=str,
        default="/home/Travor/workspaces/diffusion_policy/data/pusht/pusht_cchi_v7_replay.zarr",
    )
    parser.add_argument(
        "--dp-repo",
        type=str,
        default="/home/Travor/workspaces/diffusion_policy",
    )
    parser.add_argument(
        "--outdir",
        type=str,
        default="/mnt/d/Code/Learning/EI/EI-learning-notes/Diffusion_Policy/artifacts/phrew_runs",
        help="Parent directory for run output folders.",
    )
    parser.add_argument(
        "--chunk-hardness",
        type=str,
        default="/mnt/d/Code/Learning/EI/EI-learning-notes/Diffusion_Policy/artifacts/phrew/chunk_hardness_norm.npy",
        help="Path to chunk_hardness_norm.npy from Stage 2b.",
    )
    parser.add_argument(
        "--probe-checkpoint",
        type=str,
        default="/mnt/d/Code/Learning/EI/EI-learning-notes/Diffusion_Policy/artifacts/state_forward_probe/best_state_forward_probe.pt",
        help="Stage 1 probe checkpoint (used if Stage 2b needs to be re-run).",
    )
    parser.add_argument(
        "--script-out",
        type=str,
        default="/mnt/d/Code/Learning/EI/EI-learning-notes/Diffusion_Policy/artifacts/run_phrew_grid.sh",
    )
    parser.add_argument(
        "--script-dir",
        type=str,
        default=str(Path(__file__).resolve().parent),
        help="Directory containing stage3_train_phrew.py.",
    )
    parser.add_argument("--epochs",      type=int,   default=100)
    parser.add_argument("--batch-size",  type=int,   default=16)
    parser.add_argument("--lr",          type=float, default=1e-4)
    parser.add_argument("--temperature", type=float, default=0.1)
    parser.add_argument("--alpha",       type=float, default=1.0)
    args = parser.parse_args()

    script = generate_script(args)

    out = Path(args.script_out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(script, encoding="utf-8")
    try:
        mode = out.stat().st_mode
        out.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    except (AttributeError, NotImplementedError):
        pass

    print(f"Generated: {out}")
    print(f"  Modes : {MODES}")
    print(f"  Seeds : {SEEDS}")
    print(f"  Total : {len(MODES) * len(SEEDS)} runs")
    print(f"\nRun with:\n  bash {out}")

    print("\n--- script preview (first 40 lines) ---")
    for line in script.split("\n")[:40]:
        print(line)


if __name__ == "__main__":
    main()
