"""Generate Stage 1 DLOS-DP training commands."""
from __future__ import annotations

import argparse
import stat
from pathlib import Path


GROUPS = ["A", "B", "C", "D", "E"]

GROUP_DESCRIPTIONS = {
    "A": "baseline: no WM term",
    "B": "WM with ground-truth action (stop-grad, no gradient to ε_θ)",
    "C": "WM with final-step x0 estimate from a clean-step forward pass",
    "D": "DLOS full: WM with x̂₀|k, gradient flows through to ε_θ  ← MAIN METHOD",
    "E": "WM with x̂₀|k but stop-grad before WM: tests whether gradient path matters",
}


def build_command(
    group: str,
    seed: int,
    zarr_path: str,
    dp_repo: str,
    runs_outdir: str,
    epochs: int,
    batch_size: int,
    lr: float,
    lambda_wm: float,
    script_dir: str,
) -> str:
    run_outdir = f"{runs_outdir}/group_{group}_seed{seed}"
    cmd = (
        f"python {script_dir}/train_dlos.py"
        f" --group {group}"
        f" --seed {seed}"
        f" --epochs {epochs}"
        f" --batch-size {batch_size}"
        f" --lr {lr}"
        f" --lambda-wm {lambda_wm}"
        f" --zarr-path {zarr_path}"
        f" --dp-repo {dp_repo}"
        f" --outdir {run_outdir}"
    )
    return cmd


def generate_script(args: argparse.Namespace) -> str:
    lines: list[str] = []
    lines.append("#!/usr/bin/env bash")
    lines.append("# Auto-generated by stage1_generate_cmds.py — DO NOT EDIT MANUALLY")
    lines.append("# DLOS-DP Stage 1 command script")
    lines.append("")
    lines.append("set -euo pipefail")
    lines.append("")
    lines.append(f'ZARR_PATH="{args.zarr_path}"')
    lines.append(f'DP_REPO="{args.dp_repo}"')
    lines.append(f'RUNS_DIR="{args.outdir}"')
    lines.append("")
    lines.append("mkdir -p \"$RUNS_DIR\"")
    lines.append("")

    for group in args.groups:
        lines.append(f"# Group {group}: {GROUP_DESCRIPTIONS[group]}")
        for seed in args.seeds:
            cmd = build_command(
                group=group,
                seed=seed,
                zarr_path='"$ZARR_PATH"',
                dp_repo='"$DP_REPO"',
                runs_outdir='"$RUNS_DIR"',
                epochs=args.epochs,
                batch_size=args.batch_size,
                lr=args.lr,
                lambda_wm=args.lambda_wm,
                script_dir=str(Path(args.script_dir).resolve()),
            )
            lines.append(f"echo '>>> Running group {group} seed {seed}'")
            lines.append(cmd)
            lines.append("")

    lines.append("echo '=== All runs completed ==='")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate Stage 1 ablation training commands."
    )
    parser.add_argument(
        "--zarr-path",
        type=str,
        default="/home/Travor/workspaces/diffusion_policy/data/pusht/pusht_cchi_v7_replay.zarr",
    )
    parser.add_argument(
        "--dp-repo",
        type=str,
        default="/home/Travor/workspaces/diffusion_policy",
    )
    parser.add_argument(
        "--outdir",
        type=str,
        default="artifacts/dlos_runs",
        help="Parent directory for run output folders.",
    )
    parser.add_argument(
        "--script-out",
        type=str,
        default="artifacts/run_dlos_stage1.sh",
        help="Output path for the generated bash script.",
    )
    parser.add_argument(
        "--script-dir",
        type=str,
        default=str(Path(__file__).resolve().parent),
        help="Directory containing train_dlos.py (default: same as this script).",
    )
    parser.add_argument(
        "--groups",
        nargs="+",
        default=GROUPS,
        choices=GROUPS,
    )
    parser.add_argument(
        "--seeds",
        nargs="+",
        type=int,
        default=[42],
    )
    parser.add_argument("--epochs",     type=int,   default=100)
    parser.add_argument("--batch-size", type=int,   default=16)
    parser.add_argument("--lr",         type=float, default=1e-4)
    parser.add_argument("--lambda-wm",  type=float, default=0.1)
    args = parser.parse_args()

    script_content = generate_script(args)

    out_path = Path(args.script_out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(script_content, encoding="utf-8")

    # Make the script executable on POSIX systems
    try:
        current = out_path.stat().st_mode
        out_path.chmod(current | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    except (AttributeError, NotImplementedError):
        pass  # Windows — chmod not supported, that's fine

    print(f"Generated: {out_path}")
    print(f"  Groups : {args.groups}")
    print(f"  Seeds  : {args.seeds}")
    print(f"  Total  : {len(args.groups) * len(args.seeds)} runs")
    print(f"\nRun with:\n  bash {out_path}")

    # Also print a preview
    print("\n--- script preview ---")
    for line in script_content.split("\n")[:30]:
        print(line)
    if script_content.count("\n") > 30:
        print("  [... truncated ...]")


if __name__ == "__main__":
    main()
